integrations:
  node_exporter:
    enabled: true
    textfile_directory: /home/pi/.boiler/data
  prometheus_remote_write:
    - basic_auth:
        password: PASSWORD
        username: USERNAME
      url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
loki:
  configs:
    - clients:
        - basic_auth:
            password: PASSWORD
            username: USERNAME
          url: https://logs-prod-eu-west-0.grafana.net/api/prom/push
      name: integrations
      positions:
        filename: /tmp/positions.yaml
      target_config:
        sync_period: 10s
      scrape_configs:
        - job_name: varlogs
          static_configs:
            - targets: [localhost]
              labels:
                job: varlogs
                __path__: /home/pi/*.log
prometheus:
  configs:
    - name: integrations
      scrape_configs:
        - job_name: 'Pushgateway'
          honor_labels: true
          static_configs:
            - targets: ['localhost:9091']
      remote_write:
        - basic_auth:
            password: PASSWORD
            username: USERNAME
          url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
  global:
    scrape_interval: 60s
  wal_directory: /tmp/grafana-agent-wal
server:
  http_listen_port: 12345