{
 "title": "Boiler",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Overall heating time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "sum(scheduler_hours_heating)" }
   ]
  },
  {
   "title": "# of schedules",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "scheduler_schedules_loaded" }
   ]
  },
  {
   "title": "Next schedule",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "scheduler_next_schedule" }
   ]
  },
  {
   "title": "To intensity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "scheduler_next_intensity" }
   ]
  },
  {
   "title": "ETA ON",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "scheduler_eta_on" }
   ]
  },
  {
   "title": "Estimated heating time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "scheduler_next_hours_needed" }
   ]
  },
  {
   "title": "ETA OFF",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "scheduler_eta_off" }
   ]
  },
  {
   "title": "Deploy logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "{filename=\"/home/pi/pre_deploy.log\"}"
    }
   ]
  },
  {
   "title": "Boiler state",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "targets": [
    { "expr": "boiler_boiler_on" }
   ]
  },
  {
   "title": "Alerts",
   "type": "alertlist",
   "gridPos": { "h": 13, "w": 6, "x": 8, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Temperature outside",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "current_weather_temperature" }
   ]
  },
  {
   "title": "Calendar logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "{filename=\"/home/pi/run_module_calendar_sync.log\"}"
    }
   ]
  },
  {
   "title": "Hours to heat per intensity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "targets": [
    { "expr": "calculator_hours_needed", "legendFormat": "{{intensity}}" }
   ]
  },
  {
   "title": "Temperature and target",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 12 },
   "targets": [
    { "expr": "scheduler_next_temperature", "legendFormat": "{{intensity}}" },
    { "expr": "current_weather_temperature", "legendFormat": "Temperature" }
   ]
  },
  {
   "title": "Weather logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "expr": "{filename=\"/home/pi/run_module_weather.log\"}"
    }
   ]
  },
  {
   "title": "Hours to heat",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "targets": [
    { "expr": "scheduler_next_hours_needed", "legendFormat": "Hours needed {{intensity}}" },
    {
     "expr": "scheduler_next_hours_needed offset 1d",
     "legendFormat": "Day before {{intensity}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "((1 - rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])) / ignoring(cpu) group_left count without (cpu)(node_cpu_seconds_total{mode=\"idle\"}))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (   avg(node_memory_MemAvailable_bytes) /   avg(node_memory_MemTotal_bytes) * 100 ) "
    }
   ]
  },
  {
   "title": "Clouds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 18 },
   "targets": [
    { "expr": "current_weather_clouds" }
   ]
  },
  {
   "title": "Scheduler logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "targets": [
    {
     "expr": "{filename=\"/home/pi/run_module_scheduler.log\"}"
    }
   ]
  }
 ]
}